# Step 1: Write mode (w)
file = open("student.txt", "w")
file.write("Name: Karishma\nAge: 20\n")
file.close()

# Step 2: Read mode (r)
file = open("student.txt", "r")
print("Read Mode Output:")
print(file.read())
file.close()

# Step 3: Append mode (a)
file = open("student.txt", "a")
file.write("Course: BCA\n")
file.close()

# Step 4: Read + Write mode (r+)
file = open("student.txt", "r+")
content = file.read()
file.write("City: Kolhapur\n")
file.close()

# Step 5: Write + Read mode (w+)
file = open("student.txt", "w+")
file.write("New Data After Overwrite\n")
file.seek(0)
print("\nWrite+Read Mode Output:")
print(file.read())
file.close()

# Step 6: Append + Read mode (a+)
file = open("student.txt", "a+")
file.write("Phone: 1234567890\n")
file.seek(0)
print("\nAppend+Read Mode Output:")
print(file.read())
file.close()